spring.application.name=ms-security
server.port=8383

spring.data.mongodb.uri=YOUR_MONGODB_URI

jwt.secret=YOUR_JWT_SECRET
jwt.expiration=3600000

google.client-id=YOUR_GOOGLE_CLIENT_ID
microsoft.client-id=YOUR_MICROSOFT_CLIENT_ID

# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=YOUR_GITHUB_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_GITHUB_CLIENT_SECRET
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Microsoft OAuth2
spring.security.oauth2.client.registration.microsoft.client-id=YOUR_MICROSOFT_CLIENT_ID
spring.security.oauth2.client.registration.microsoft.client-secret=YOUR_MICROSOFT_CLIENT_SECRET
spring.security.oauth2.client.registration.microsoft.scope=openid,profile,email
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.microsoft.redirect-uri=http://localhost:8383/login/oauth2/code/microsoft

spring.security.oauth2.client.provider.microsoft.authorization-uri=YOUR_MICROSOFT_AUTH_URI
spring.security.oauth2.client.provider.microsoft.token-uri=YOUR_MICROSOFT_TOKEN_URI
spring.security.oauth2.client.provider.microsoft.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.microsoft.jwk-set-uri=YOUR_MICROSOFT_JWK_URI
spring.security.oauth2.client.provider.microsoft.user-name-attribute=sub

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Recaptcha
recaptcha.secret=YOUR_RECAPTCHA_SECRET
recaptcha.site-key=YOUR_RECAPTCHA_SITE_KEY