spring.application.name=ms-security
server.port=8383

spring.data.mongodb.uri=mongodb+srv://christianramirez27692:crisca@cluster0.jhieoxi.mongodb.net/?appName=Cluster0
spring.mongodb.database=db_security

jwt.secret=aaa
jwt.expiration=3600000
