spring.application.name=ms-security
server.port=8081
spring.security.oauth2.client.registration.google.client-id=TU_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=TU_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile
spring.mongodb.uri=TU_MONGODB_URI
spring.mongodb.database=db_security
jwt.secret=TU_JWT_SECRET
jwt.expiration=3600000